DB_URL=postgres://postgres:postgres@localhost:5432/taskdb?sslmode=disable

migrate-create:
	migrate create -ext sql -dir migrations -seq init_schema

migrate-up:
	migrate -path migrations -database $(DB_URL) -verbose up

migrate-down:
	migrate -path migrations -database $(DB_URL) -verbose down

migrate-force:
	migrate -path migrations -database $(DB_URL) force 1
