DB_URL="postgres://postgres:postgres@localhost:5432/taskdb?sslmode=disable"

migrate-create:
	migrate create -ext sql -dir db/migrations -seq init_schema

migrate-up:
	migrate -path db/migrations -database $(DB_URL) -verbose up

migrate-down:
	migrate -path db/migrations -database $(DB_URL) -verbose down

migrate-force:
	migrate -path db/migrations -database $(DB_URL) force 1